### ISSUE TITLE
lost signal when configuring the iio object  in Matlab2017b

### ISSUE THREAD

**Issue by LimoJ** [analogdevicesinc/libiio-matlab#4]
hi!
i get a problem and don't know  how to solve it.

matlab 2017 b
simulink

when i use the example in  https://github.com/analogdevicesinc/MathWorks_tools   , i get some problems. i want to change the ip address to what my board own, but some signal lost ,and matlab throw out the warning "Port number 1 specified in 'port_label' drawing command exceeds the number of input ports of 'fmcomms5/FMCOMMS5/MATLAB System1'".

![erroe](https://user-images.githubusercontent.com/8305920/39954697-d1bf6042-55f5-11e8-8956-fc8c17e232d2.png)

                                                                                                                                        Thanks.

**Comment by tfcollins** [comment]
Are you changing anything else in the model?

**Comment by LimoJ** [comment]
I didn‘t edit any files. I just add the libiio-matlab-master path to matlab and open the .slx file in simulink. I use MathWorks_tools-2017b branch which I think is match with the matlab version.

**Comment by tfcollins** [comment]
Make sure the current MATLAB path is "hil_models\fmcomms5_data_stream" which contains the correct models.  If you are not in that folder the Simulink model may utilize the wrong system objects.

**Comment by LimoJ** [comment]
Thank you for your generous response. It works.
